### PR TITLE
Add Bad Idea Ai BAD token to Shibarium mainnet

### PR DESCRIPTION
**Pull request by MaximousDarwin**
Hi team,
Created this pull request to help Bad Idea Ai project adding their token data to Shibarium.
Thanks in advance.

### CODE REVIEW

**Comment by vinayak0035** [comment]
BAD AI is already added

**Comment by MaximousDarwin** [comment]
Hi @vinayak0035 , looks like it was added on Ethereum before, but still missing in Shibarium in this repository. An I missing something?

Thank you.

**Comment by vinayak0035** [comment]
It is already on eth side, so info is accessible in json with child token, but if want we can deploy on shibarium also not an issue

**Comment by MaximousDarwin** [comment]
Ok @vinayak0035  I see. I assumed the logo with the child address as name on shibarium side is necessary to be displayed on ShibaSwap (Shibarium), since the logo for the child address didn't exist yet.
For the logo I guess it might be necessary, also also to access the logo for the child address from the CDN.

But let me know what works best for you 😊

**Comment by vinayak0035** [comment]
we can have on child also

**Review by vinayak0035 — APPROVED** [review]

**Pull request merged**
